load clown
surface(peaks,flipud(X),...
   'FaceColor','texturemap',...
   'EdgeColor','none',...
   'CDataMapping','direct')
colormap(map)        	%²Î¿¼Í¼20-4£¨a£©
view(-35,45)            	%²Î¿¼Í¼20-4£¨b£©
